### PR TITLE
add reset capacity

### PR DESCRIPTION
**Pull request by MuadDibVV**

### CODE REVIEW

**Comment by pajikos** [comment]
Hi MuadDibVV, thank you for your PR. 
I have no doubt that a reset is a useful function, but could you please update README.md to explain, why and when it is useful? Someone may have no idea what it is for.

**Comment by MuadDibVV** [comment]
Hi Pavel,

 

I added an entry in the FAQ. Is it sufficient ?

 

Thanks

 

De : Pavel Sklenář <notifications@github.com> 
Envoyé : dimanche 21 février 2021 13:44
À : pajikos/sms-gammu-gateway <sms-gammu-gateway@noreply.github.com>
Cc : MuadDibVV <vvuillaume@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [pajikos/sms-gammu-gateway] add reset capacity (#17)

 

Hi MuadDibVV, thank you for your PR.
I have no doubt that a reset is a useful function, but could you please update README.md to explain, why and when it is useful? Someone may have no idea what it is for.

**Review by pajikos — APPROVED** [review]
Thank you for desc.

**Comment by MuadDibVV** [comment]
Thank you

 

De : Pavel Sklenář <notifications@github.com> 
Envoyé : dimanche 21 février 2021 17:55
À : pajikos/sms-gammu-gateway <sms-gammu-gateway@noreply.github.com>
Cc : MuadDibVV <vvuillaume@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [pajikos/sms-gammu-gateway] add reset capacity (#17)

 

Merged #17 <https://github.com/pajikos/sms-gammu-gateway/pull/17>  into master.

**Comment by rchovan** [comment]
Hi, I think it does not work. 
API call to reset 
```
curl http://192.168.2.5:5000/reset
<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```
API call to signal 
```
curl http://192.168.2.5:5000/signal
{"SignalStrength": -77, "SignalPercent": 54, "BitErrorRate": -1}
```

**Pull request merged**
